server:
  port: 8081
  servlet:
    session:
      timeout: PT12H
spring:
    datasource:
        url: jdbc:mysql://123.57.6.171:3306/miaotu_formal?useUnicode=true&characterEncoding=utf-8
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: c2bwERZKB3H1








